const users = [
  { name: "Chencho" },
  { name: "John" },
  { name: "David" },
  { name: "Robert" },
  { name: "Peter" },
  { name: "Simson" },
  { name: "Tim" },
  { name: "Tony" },
  { name: "Ruben" },
  { name: "Miller" },
  { name: "Rock" },
  { name: "Stev" },
  { name: "Haakon" },
  { name: "Samuel" },
  { name: "Jerico" },
  { name: "Jackie" },
  { name: "Adam" },
  { name: "Jackson" },
  { name: "Scot" },
  { name: "Simon" },
  { name: "Lars" },
  { name: "Rachel" },
  { name: "Eve" },
  { name: "Undertaker" },
  { name: "Conor" },
  { name: "Oliver" },
];

export default users;
